---
kind: Service
spec:
  type: LoadBalancer
  ports:
  - protocol: TCP
    name: spark
    targetPort: 8080
  selector:
    app: master
apiVersion: v1
metadata:
  name: spark

---
kind: Deployment
spec:
  template:
    spec:
      containers:
      - name: container
        env:
        - name: SERVERIP
          value: "10.10.12.216"
        image: nsc-registry.infra.ericsson.se:5000/run_always:latest
        ports:
        - containerPort: 8080
        - containerPort: 7077

        resources:
          requests:
            cpu: '1'
            memory: 1Gi
          limits:
            cpu: '2'
            memory: 2Gi
      nodeSelector:
        quobyte_client: "true"
    metadata:
      labels:
        app: master
  replicas: 1
apiVersion: extensions/v1beta1
metadata:
  name: container
